---
output:
  pdf_document: default
papersize: a4
geometry: margin=0.75in
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
# devtools::install_github("majazaloznik/UMARaccessR", dependencies = FALSE)
# devtools::install_github("majazaloznik/UMARvisualisR", dependencies = FALSE)

library(UMARaccessR)
library(UMARvisualisR)
extrafont::loadfonts()

```

```{r, fig.width = 22/2.54, fig.height =11 /2.54, fig.fullwidth=TRUE, echo = FALSE,dev = "cairo_pdf", message = FALSE, warning = FALSE, results= 'hide'}
con <- DBI::dbConnect(RPostgres::Postgres(),
                      dbname = "sandbox",
                      host = "localhost",
                      port = 5432,
                      user = "postgres",
                      password = Sys.getenv("PG_local_PG_PSW"),
                      client_encoding = "utf8")
# set schema search path
x <- DBI::dbExecute(con, "set search_path to test_platform")

# get input data to know what to plot
df <- readxl::read_excel("db_series-2023-03-22.xlsx", "selection")
spl <- split(df, df$chart_no)
log_odd <- as.list(rep(c(0,1), length.out = length(spl)))
wb <- prep_workbook()
{
  log <- paste0("log_", format(Sys.time(), "%d-%b-%Y %H.%M.%S"), ".log")
  file_con <- file(log, open = "wt", encoding = "UTF-8")
  sink(file_con)
  purrr::walk2(spl, log_odd, \(x,y)
               UMARvisualisR::multiline_pipeline(x, con = con,
                                  xmin = "2011-01-01",
                                  xmax=NULL,
                                  draw_charts = TRUE,
                                  export_excel = TRUE,
                                  wb = wb, odd = y))
  sink()
  close(file_con)
}
openxlsx::saveWorkbook(wb, file = "test.xlsx", overwrite = TRUE)
```


    
