#' script for data that is saved into R/sysdata.rda

meta <- data.frame(file_path = c("tests/testthat/testdata/Drzavni_proracun_1992-2023.xlsx",
                                 "tests/testthat/testdata/Bilance_proracunov_obcin_1992-2023.xlsx",
                                 "tests/testthat/testdata/Zavod_za_pokojninsko_in_invalidsko_zavarovanje_1992-2023.xlsx",
                                 "tests/testthat/testdata/Zavod_za_zdravstveno_zavarovanje_Slovenije_1992-2023.xlsx",
                                 "tests/testthat/testdata/Konsolidirana_bilanca_javnega_financiranja_1992-2023.xlsx"),
                   table_name = c("DP", "OB", "ZPIZ", "ZZZS", "KBJF"),
                   sheet_name = c("MESPROR", "OBCINE", "ZPIZ", "ZZZS", "GLOBALNA"))


konto_codes <- data.frame(description =c("TEKO\u010cI PRIHODKI" ,
                                         "TEKOCI PRIHODKI",
                                         "PREJETA MINUS DANA POSOJILA IN SPREMEMBE KAPITALSKIH DELE\u017dEV",
                                         "PREJETA MINUS DANA POSOJILA IN SPREMEMBE KAPITALSKIH  DELEEV",
                                         "PREJETA MINUS DANA POSOJILA IN SPREMEMBE KAPITALSKIH DELE\u017dEV\u017e",
                                         "NETO ZADOL\u017dEVANJE" ,
                                         "NETO ZADOL\u017dEVANJE (ODPLA\u010cILA) DOLGA",
                                         "POVE\u010cANJE (ZMANJ\u0160ANJE) SREDSTEV NA RA\u010cUNIH" ,
                                         "(I.+IV.+VII.-II.-V.-VIII.)" ,
                                         "NETO FINANCRANJE",
                                         "NETO FINANCIRANJE" ,
                                         "PRESE\u017dEK (PRIMANJKLJAJ)",
                                         "PRORAČUNSKI PRESEŽEK (PRIMANJKLJAJ)",
                                         "PRIMARNI PRESE\u017dEK (PRIMANJKLJAJ)",
                                         "TEKOČI PRESEŽEK (PRIMANJKLJAJ)",
                                         "PLA\u010cE IN DRUGI IZDATKI ZAPOSLENIM" ,
                                         "PRISPEVKI DELODAJALCEV ZA SOCIALNO VARNOST",
                                         "IZDATKI ZA BLAGO IN STORITVE" ),
                          code = c(901, 901,902, 902,902,903, 903, 904, 904, 905, 905, 906, 906, 907, 908, 911, 912, 913))

# list of series for KBJF rates tables
kbjf_series_list_eo <- list(
  "MF--KBJF--001--7--M",
  "MF--KBJF--003--70--M",
  "MF--KBJF--005--7000--M",
  "MF--KBJF--006--7001--M",
  "MF--KBJF--016--7030--M",
  "MF--KBJF--021--7040--M",
  "MF--KBJF--023--7042--M",
  "MF--KBJF--007--701--M",
  "MF--KBJF--035--71--M",
  "MF--KBJF--081--78--M",
  "MF--KBJF--050--72--M",
  "MF--KBJF--063--73--M",
  "MF--KBJF--073--74--M",
  "MF--KBJF--091--4--M",
  "MF--KBJF--094--400--M",
  "MF--KBJF--095--413300--M",
  "MF--KBJF--097--401--M",
  "MF--KBJF--098--413301--M",
  "MF--KBJF--099--413310--M",
  "MF--KBJF--101--402--M",
  "MF--KBJF--102--413302--M",
  "MF--KBJF--103--403--M",
  "MF--KBJF--110--404--M",
  "MF--KBJF--115--409--M",
  "MF--KBJF--124--411--M",
  "MF--KBJF--119--41--M",
  "MF--KBJF--124--411--M",
  "MF--KBJF--148--42--M",
  "MF--KBJF--160--43--M",
  "MF--KBJF--173--45--M",
  "MF--KBJF--182--906--M",
  "MF--KBJF--183--907--M")

# list of series for the 12 month cumulative tables
kbjf_series_list_12mK <- list(
  "MF--KBJF--001--7--M",
  "MF--KBJF--002--901--M",
  "MF--KBJF--003--70--M",
  "MF--KBJF--004--700--M",
  "MF--KBJF--007--701--M",
  "MF--KBJF--012--702--M",
  "MF--KBJF--015--703--M",
  "MF--KBJF--020--704--M",
  "MF--KBJF--030--705--M",
  "MF--KBJF--033--706--M",
  "MF--KBJF--035--71--M",
  "MF--KBJF--050--72--M",
  "MF--KBJF--063--73--M",
  "MF--KBJF--073--74--M",
  "MF--KBJF--081--78--M",
  "MF--KBJF--091--4--M",
  "MF--KBJF--092--40--M",
  "MF--KBJF--093--911--M",
  "MF--KBJF--096--912--M",
  "MF--KBJF--100--913--M",
  "MF--KBJF--103--403--M",
  "MF--KBJF--110--404--M",
  "MF--KBJF--115--409--M",
  "MF--KBJF--119--41--M",
  "MF--KBJF--120--410--M",
  "MF--KBJF--124--411--M",
  "MF--KBJF--134--412--M",
  "MF--KBJF--136--413--M",
  "MF--KBJF--143--414--M",
  "MF--KBJF--148--42--M",
  "MF--KBJF--160--43--M",
  "MF--KBJF--173--45--M",
  "MF--KBJF--182--906--M",
  "MF--KBJF--183--907--M")

# name of final rows in  KBJF rates tables
kbjf_row_names_eo <-c("SKUPAJ PRIHODKI",
              "Davčni prihodki brez soc.p.",
              "Dohodnina",
              "Davek od dohodkov pravnih oseb",
              "Davki na nepremičnine",
              "Davek na dodano vrednost",
              "Trošarine (akcize)",
              "PRISPEVKI ZA SOCIALNO VARNOST",
              "NEDAVČNI PRIHODKI",
              "PREJETA SREDSTVA IZ EU IN IZ DRUGIH DRŽAV",
              "Ostalo",
              "SKUPAJ ODHODKI",
              "Plače in drugi stroški dela",
              "Izdatki za blago in storitve",
              "Plačila obresti",
              "REZERVE",
              "TRANSFERI POSAMEZNIKOM IN GOSPODINJSTVOM",
              "Ostali tekoči transferi",
              "Izdatki za investicije",
              "PLAČILA SREDSTEV V PRORAČUN  EU",
              "JAVNOFINANČNI SALDO",
              "PRIMARNI SALDO")

# name of final rows in 12 month cumulative tables.
kbjf_row_names_12Mk <-c("SKUPAJ PRIHODKI",
                      "TEKOČI PRIHODKI",
                      "DAVČNI PRIHODKI",
                      "DAVKI NA DOHODEK IN DOBIČEK",
                      "PRISPEVKI ZA SOCIALNO VARNOST",
                      "DAVKI NA PLAČILNO LISTO IN DELOVNO SILO",
                      "DAVKI NA PREMOŽENJE",
                      "DOMAČI DAVKI NA BLAGO IN STORITVE",
                      "DAVKI NA MEDNARODNO TRGOVINO IN TRANSAKCIJE",
                      "DRUGI DAVKI",
                      "NEDAVČNI PRIHODKI",
                      "KAPITALSKI PRIHODKI",
                      "PREJETE DONACIJE",
                      "TRANSFERNI PRIHODKI",
                      "PREJETA SREDSTVA IZ EU IN IZ DRUGIH DRŽAV",
                      "SKUPAJ ODHODKI",
                      "TEKOČI ODHODKI",
                      "PLAČE IN DRUGI IZDATKI ZAPOSLENIM, VKLJUČNO S PRISPEVKI ZA SOCIALNO VARNOST",
                      "IZDATKI ZA BLAGO IN STORITVE",
                      "PLAČILA DOMAČIH IN TUJIH OBRESTI",
                      "REZERVE",
                      "TEKOČI TRANSFERI",
                      "SUBVENCIJE",
                      "TRANSFERI POSAMEZNIKOM IN GOSPODINJSTVOM",
                      "TRANSFERI NEPRIDOBITNIM ORGANIZACIJAM IN USTANOVAM, DRUGI TEKOČI DOMAČI TRANSFERI",
                      "TEKOČI TRANSFERI V TUJINO",
                      "INVESTICIJSKI ODHODKI",
                      "INVESTICIJSKI TRANSFERI",
                      "PLAČILA SREDSTEV V PRORAČUN EU",
                      "JAVNOFINANČNI SALDO",
                      "PRIMARNI SALDO")

usethis::use_data(meta,
                  konto_codes,
                  kbjf_series_list_eo,
                  kbjf_series_list_12mK,
                  kbjf_row_names_eo,
                  internal = TRUE, overwrite = TRUE)
